export const mockLots = [
  {
    id: "L001",
    status: "Disponible",
    subStatus: "En promoción",
    plan: "Plano General",
    owner: "CCLF",
    surface: "500 m²",
    price: "$50,000",
    location: "Sector Norte",
    descriptionPoints: ["Vista al lago", "Acceso pavimentado", "Servicios completos"],
    images: [
      "/placeholder.svg?width=600&height=400&text=Lote+L001+Imagen+1",
      "/placeholder.svg?width=600&height=400&text=Lote+L001+Imagen+2",
      "/placeholder.svg?width=600&height=400&text=Lote+L001+Imagen+3",
    ],
  },
  {
    id: "L002",
    status: "Vendido",
    subStatus: "Vendido",
    plan: "Plano General",
    owner: "Juan Pérez",
    surface: "600 m²",
    price: "$65,000",
    location: "Sector Sur",
    descriptionPoints: ["Cerca del Club House", "Arboleda añosa"],
    images: ["/placeholder.svg?width=600&height=400&text=Lote+L002+Imagen+1"],
  },
  {
    id: "L003",
    status: "Reservado",
    subStatus: "Reservado",
    plan: "Plano Sector A",
    owner: "Ana Gómez",
    surface: "550 m²",
    price: "$58,000",
    location: "Sector Este",
    descriptionPoints: ["Esquina privilegiada", "Vista panorámica"],
    images: ["/placeholder.svg?width=600&height=400&text=Lote+L003+Imagen+1"],
  },
  {
    id: "L004",
    status: "En Construccion",
    subStatus: "Disponible",
    plan: "Plano Sector B",
    owner: "Carlos López",
    surface: "700 m²",
    price: "$72,000",
    location: "Sector Oeste",
    descriptionPoints: ["Amplio frente", "Ideal para familias"],
    images: ["/placeholder.svg?width=600&height=400&text=Lote+L004+Imagen+1"],
  },
  {
    id: "L005",
    status: "Disponible",
    subStatus: "Disponible",
    plan: "Plano General",
    owner: "CCLF",
    surface: "520 m²",
    price: "$52,000",
    location: "Sector Norte",
    descriptionPoints: ["Excelente ubicación", "Listo para construir"],
    images: ["/placeholder.svg?width=600&height=400&text=Lote+L005+Imagen+1"],
  },
]

export const mockUser = {
  id: "U001",
  name: "María González",
  email: "maria.gonzalez@email.com",
  phone: "+54 11 1234-5678",
  role: "Administrador",
  avatar: "/placeholder.svg?width=100&height=100&text=MG",
  joinDate: "2023-01-15",
  reservations: [
    {
      id: "R001",
      lotId: "L003",
      date: "2024-06-10",
      status: "Activa",
      amount: "$58,000",
    },
    {
      id: "R002",
      lotId: "L001",
      date: "2024-05-15",
      status: "Completada",
      amount: "$50,000",
    },
  ],
  activityLog: [
    {
      id: "A001",
      action: "Reservó lote L003",
      date: "2024-06-10 14:30",
      details: "Reserva confirmada por $58,000",
    },
    {
      id: "A002",
      action: "Editó información de lote L001",
      date: "2024-06-09 10:15",
      details: "Actualizó descripción y precio",
    },
    {
      id: "A003",
      action: "Aplicó promoción a lote L001",
      date: "2024-06-08 16:45",
      details: "Descuento del 10% aplicado",
    },
  ],
}
